# Generated by Django 6.0.4 on 2026-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("patient", "Пациент"), ("doctor", "Врач"), ("admin", "Администратор")],
                default="patient",
                max_length=20,
            ),
        ),
    ]
