# Generated by Django 6.0.4 on 2026-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("therapist", "Терапевт"),
                            ("cardiologist", "Кардиолог"),
                            ("pediatrician", "Педиатр"),
                            ("neurologist", "Невролог"),
                            ("lab", "Лабораторная диагностика"),
                        ],
                        max_length=50,
                        verbose_name="Специализация",
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0, verbose_name="Стаж (лет)")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="doctors/", verbose_name="Фото")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
    ]
