# Generated by Django 6.0.4 on 2026-05-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slot_duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="doctor",
            name="work_end",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="work_start",
            field=models.TimeField(default="09:00"),
        ),
    ]
