# Generated by Django 6.0.4 on 2026-05-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_doctor_slot_duration_doctor_work_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="slot_duration",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="work_end",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="work_start",
        ),
    ]
