# Generated by Django 6.0.4 on 2026-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="doctors",
            field=models.ManyToManyField(blank=True, related_name="services", to="core.doctor"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
