# Generated by Django 6.0.4 on 2026-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_time_alter_appointment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
