# Generated by Django 6.0.4 on 2026-05-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appointment_time_alter_appointment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Заключение врача")),
                ("file", models.FileField(blank=True, null=True, upload_to="diagnostics/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="appointments.appointment",
                    ),
                ),
            ],
        ),
    ]
